const data=window.SPORTS_DATA;const config=window.DASHBOARD_CONFIG||{};const assets=window.SPORTS_ASSETS||{logos:{},heroImages:{}};const $=(id)=>document.getElementById(id);const root=document.documentElement;
root.style.setProperty('--accent',config.accent||'#e10600');root.style.setProperty('--accent-2',config.accentAlt||'#f4f4f4');root.style.setProperty('--ticker-speed',`${config.tickerSpeedSeconds||38}s`);
const logoMarkup=(code)=>assets.logos?.[code]?`<img src="${assets.logos[code]}" alt="${code} logo" loading="eager" onerror="this.remove();this.parentElement.textContent='${code}'">`:code;
window.addEventListener('load',()=>setTimeout(()=>$('bootScreen')?.classList.add('done'),1850));
function updateClock(){const now=new Date();$('clock').textContent=now.toLocaleTimeString([],{hour:'numeric',minute:'2-digit',hour12:config.timeFormat!=='24h'});$('date').textContent=now.toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'}).toUpperCase();$('lastUpdate').textContent=now.toLocaleTimeString();}updateClock();setInterval(updateClock,1000);
const enabledSports=config.enabledSports||['NFL','NBA','MLB','NHL','NCAAF','F1','INDYCAR'];const favoriteTokens=Object.values(config.favorites||{}).flat();const containsFavorite=(s)=>favoriteTokens.some((t)=>[s.awayMark,s.homeMark,s.awayName,s.homeName].join(' ').includes(t));const statusScore=(status='')=>{const s=status.toUpperCase();if(s.includes('LIVE')||s.includes('INNING')||s.includes('LAP'))return config.priorityWeights?.live||100;if(s.includes('FINAL'))return config.priorityWeights?.final||8;if(s.includes('FEATURED')||s.includes('RACE WEEK')||s.includes('UPCOMING'))return config.priorityWeights?.upcoming||20;return 10;};
const heroSlides=data.heroSlides.filter((s)=>enabledSports.includes(s.league)).map((s)=>({...s,priority:statusScore(s.status)+(containsFavorite(s)?(config.priorityWeights?.favorite||35):0)})).sort((a,b)=>b.priority-a.priority);
function detectMode(slide){const hour=new Date().getHours();if(hour>=(config.modes?.quietHoursStart??23)||hour<(config.modes?.quietHoursEnd??7))return['NIGHT WATCH','Quiet-hour presentation with reduced visual intensity'];if(['F1','INDYCAR'].includes(slide.league)&&config.modes?.raceControl)return['RACE CONTROL',`${slide.league} has command priority`];if(slide.league==='NFL'&&config.modes?.redZone&&new Date().getDay()===0)return['RED ZONE','Sunday football priority is active'];return['COMMAND MODE',`${slide.league} currently owns the highest priority score`];}
$('sportStrip').innerHTML=enabledSports.map((sport)=>`<span class="sport-chip" data-sport="${sport}">${sport}</span>`).join('');function setActiveSport(sport){document.querySelectorAll('.sport-chip').forEach((c)=>c.classList.toggle('active',c.dataset.sport===sport));}function tickerHTML(items){return[...items,...items].map((text)=>`<span class="ticker-item">${text}</span>`).join('');}
$('tickerStack').innerHTML=data.tickerLanes.map((lane,index)=>`<section class="ticker ticker-lane"><div class="ticker-label">${lane.label}</div><div class="ticker-window"><div class="ticker-track ${lane.direction==='right'?'reverse':''}" style="animation-duration:${(config.tickerSpeedSeconds||38)+index*4}s">${tickerHTML(lane.items)}</div></div></section>`).join('');$('upcomingTicker').innerHTML=[...data.upcoming,...data.upcoming].map(([tag,text])=>`<span class="ticker-item"><b>${tag}</b>${text}</span>`).join('');
const ribbonEvents=heroSlides.map((h)=>({league:h.league,mark:h.awayMark,match:`${h.awayMark} · ${h.homeMark}`,meta:`${h.status} · ${h.gameMeta}`,score:h.score,live:/LIVE|INNING|LAP/.test(h.status.toUpperCase())}));$('arenaRibbon').innerHTML=[...ribbonEvents,...ribbonEvents].map((e)=>`<article class="score-tile ${e.live?'live':''}"><div class="tile-league">${e.league}${e.live?' · LIVE':''}</div><div class="tile-mark">${logoMarkup(e.mark)}</div><div><div class="tile-match">${e.match}</div><div class="tile-meta">${e.meta}</div></div><div class="tile-score">${e.score}</div></article>`).join('');
const visibleLeagues=data.leagues.filter((l)=>enabledSports.includes(l.name));$('leagueGrid').innerHTML=visibleLeagues.map((league)=>`<article class="league-card"><div class="league-card-header"><span class="league-name">${league.name}</span><span class="card-status">${league.status}</span></div>${league.games.map((g)=>`<div class="game-row"><div><div class="game-team">${g[0]}</div><div class="game-meta">${g[1]}</div></div><div class="game-score">${g[2]}</div></div>`).join('')}</article>`).join('');
const m=data.michigan;$('michiganModule').innerHTML=`<article class="michigan-card"><div class="michigan-summary"><div class="michigan-brand"><div class="michigan-logo">${logoMarkup('MICH')}</div><div><span class="card-status">${m.conference}</span><h2>${m.team}</h2><p>${m.record} · ${m.ranking}</p></div></div><div class="next-game"><span>NEXT GAME</span><strong>${m.nextGame.opponent}</strong><p>${m.nextGame.date} · ${m.nextGame.time} · ${m.nextGame.network}</p><small>${m.nextGame.venue}</small></div></div><div class="michigan-grid"><div><h3>UPCOMING SCHEDULE</h3>${m.schedule.map((g)=>`<div class="schedule-row"><span>${g[1]}</span><strong>${g[0]}</strong><em>${g[2]}</em></div>`).join('')}</div><div><h3>TEAM NOTES</h3>${m.notes.map((n)=>`<p class="team-note">${n}</p>`).join('')}</div></div></article>`;
$('raceCards').innerHTML=data.races.map((r)=>`<article class="race-card"><div class="card-status">${r.series}</div><div class="race-title">${r.title}</div><div class="race-meta">${r.meta}</div><div class="position-list">${r.positions.map((p)=>`<div class="position"><div class="position-num">${p[0]}</div><div>${p[1]}</div><div>${p[2]}</div></div>`).join('')}</div></article>`).join('');
let heroIndex=0;function renderHero(){const h=heroSlides[heroIndex];const vals={heroLeague:h.league,heroStatus:h.status,heroTitle:h.title,awayName:h.awayName,awayRecord:h.awayRecord,homeName:h.homeName,homeRecord:h.homeRecord,gameMeta:h.gameMeta,score:h.score,venue:h.venue};Object.entries(vals).forEach(([id,v])=>$(id).textContent=v);$('awayMark').innerHTML=logoMarkup(h.awayMark);$('homeMark').innerHTML=logoMarkup(h.homeMark);const photo=assets.heroImages?.[h.league];$('heroPhoto').style.backgroundImage=photo?`linear-gradient(90deg,rgba(5,6,8,.96) 0%,rgba(5,6,8,.78) 45%,rgba(5,6,8,.32) 100%),url('${photo}')`:'';$('priorityScore').textContent=`PRIORITY ${String(h.priority).padStart(3,'0')}`;$('intelRow').innerHTML=[['MODE',h.league],['STATUS',h.status],['FAVORITE',containsFavorite(h)?'YES':'NO']].map(([k,v])=>`<div class="intel"><span>${k}</span><strong>${v}</strong></div>`).join('');const[mode,reason]=detectMode(h);$('modeName').textContent=mode;$('modeReason').textContent=reason;$('dashboard').dataset.mode=mode.toLowerCase().replaceAll(' ','-');setActiveSport(h.league);const progress=$('heroProgress');progress.style.animation='none';requestAnimationFrame(()=>progress.style.animation=`heroProgress ${config.heroRotationMs||10500}ms linear infinite`);}renderHero();setInterval(()=>{const hero=$('hero');hero.classList.add('switching');setTimeout(()=>{heroIndex=(heroIndex+1)%heroSlides.length;renderHero();hero.classList.remove('switching');},280);},config.heroRotationMs||10500);
let storyIndex=0;const stories=data.stories.filter(([league])=>enabledSports.includes(league));function renderStory(){const[league,headline,summary]=stories[storyIndex];$('storyLeague').textContent=league;$('storyHeadline').textContent=headline;$('storySummary').textContent=summary;$('storyCounter').textContent=`${String(storyIndex+1).padStart(2,'0')} / ${String(stories.length).padStart(2,'0')}`;const image=assets.heroImages?.[league];$('storyImage').style.backgroundImage=image?`linear-gradient(rgba(5,6,8,.18),rgba(5,6,8,.64)),url('${image}')`:'';}renderStory();setInterval(()=>{storyIndex=(storyIndex+1)%stories.length;renderStory();},config.storyRotationMs||8200);window.addEventListener('error',()=>{$('dataStatus').textContent='DISPLAY DEGRADED';});
