window.SPORTS_DATA={events:[
{id:"DET-GB",league:"NFL",status:"UPCOMING",title:"NFC NORTH PRIME TIME",away:"DET",awayName:"LIONS",home:"GB",homeName:"PACKERS",start:"2026-09-13T00:20:00Z",venue:"LAMBEAU FIELD · GREEN BAY",network:"NBC",odds:{spread:"DET -2.5",moneyline:"DET -135 · GB +115",total:"O/U 47.5"}},
{id:"BOS-DEN",league:"NBA",status:"UPCOMING",title:"PRIMETIME BASKETBALL",away:"BOS",awayName:"CELTICS",home:"DEN",homeName:"NUGGETS",start:"2026-10-22T01:00:00Z",venue:"BALL ARENA · DENVER",network:"TNT",odds:{spread:"BOS -1.5",moneyline:"BOS -120 · DEN +105",total:"O/U 228.5"}},
{id:"HOU-SEA",league:"MLB",status:"LIVE · TOP 7",title:"AMERICAN LEAGUE SHOWDOWN",away:"HOU",awayName:"ASTROS",home:"SEA",homeName:"MARINERS",start:"2026-08-05T01:40:00Z",venue:"T-MOBILE PARK · SEATTLE",network:"MLB.TV",score:"4 — 3",detail:"TOP 7 · 1 OUT",odds:{spread:"HOU -1.5",moneyline:"HOU -125 · SEA +110",total:"O/U 8.5"}},
{id:"EDM-FLA",league:"NHL",status:"UPCOMING",title:"HOCKEY NIGHT",away:"EDM",awayName:"OILERS",home:"FLA",homeName:"PANTHERS",start:"2026-10-11T00:30:00Z",venue:"AMERANT BANK ARENA",network:"ESPN",odds:{spread:"FLA -1.5",moneyline:"EDM +115 · FLA -135",total:"O/U 6.5"}},
{id:"MICH-TEX",league:"NCAAF",status:"UPCOMING",title:"SATURDAY SPOTLIGHT",away:"TEX",awayName:"LONGHORNS",home:"MICH",homeName:"WOLVERINES",start:"2026-09-12T16:00:00Z",venue:"MICHIGAN STADIUM · ANN ARBOR",network:"FOX",odds:{spread:"MICH -3.5",moneyline:"MICH -165 · TEX +140",total:"O/U 44.5"}},
{id:"F1-SPA",league:"F1",status:"RACE WEEK",title:"BELGIAN GRAND PRIX",away:"NOR",awayName:"NORRIS",home:"PIA",homeName:"PIASTRI",start:"2026-08-30T13:00:00Z",venue:"SPA-FRANCORCHAMPS",network:"ESPN",detail:"LIGHTS OUT",odds:{spread:"WINNER",moneyline:"NOR +180 · PIA +220",total:"TOP 6 FINISH"}},
{id:"INDY-RA",league:"INDYCAR",status:"RACE WEEK",title:"ROAD AMERICA",away:"PAL",awayName:"PALOU",home:"OWD",homeName:"O’WARD",start:"2026-08-23T19:00:00Z",venue:"ELKHART LAKE, WISCONSIN",network:"FOX",detail:"GREEN FLAG",odds:{spread:"WINNER",moneyline:"PAL +250 · OWD +400",total:"TOP 5 FINISH"}}
],tickerLanes:[{league:"NFL",direction:"left"},{league:"NBA",direction:"right"},{league:"MLB",direction:"left"},{league:"NHL",direction:"right"},{league:"NCAAF",direction:"left"},{league:"F1",direction:"right"},{league:"INDYCAR",direction:"left"}],
leaguePages:[
{league:"NFL",headline:"THE WEEK BELONGS TO DIVISION GAMES",summary:"Sunday night in Green Bay headlines a full national slate, with last week's results and every major window presented together.",lead:{away:"DET",home:"GB",label:"SUNDAY NIGHT FOOTBALL",time:"SUN · 7:20 PM CT",odds:"DET -2.5 · O/U 47.5"},results:[{away:"KC",home:"BUF",score:"27–24",detail:"FINAL"},{away:"SF",home:"PHI",score:"31–20",detail:"FINAL"},{away:"BAL",home:"CIN",score:"23–17",detail:"FINAL"}],upcoming:[{away:"DET",home:"GB",detail:"SUN · 7:20 PM CT · NBC",odds:"DET -2.5"},{away:"DAL",home:"NYG",detail:"SUN · 3:25 PM CT · FOX",odds:"DAL -4.5"},{away:"MIA",home:"NYJ",detail:"MON · 7:15 PM CT · ESPN",odds:"MIA -1.5"}],marquee:[{away:"KC",home:"BUF",detail:"AFC heavyweight rematch"},{away:"SF",home:"PHI",detail:"NFC measuring-stick game"},{away:"BAL",home:"CIN",detail:"Prime-time division pressure"}]},
{league:"NBA",headline:"THE NATIONAL SLATE OPENS WITH STAR POWER",summary:"Results, upcoming television windows and the week's headline matchups rotate through one compact basketball desk.",lead:{away:"BOS",home:"DEN",label:"OPENING NIGHT",time:"TUE · 8:00 PM CT",odds:"BOS -1.5 · O/U 228.5"},results:[{away:"LAL",home:"PHX",score:"118–112",detail:"FINAL"},{away:"MIL",home:"NYK",score:"104–101",detail:"FINAL"}],upcoming:[{away:"BOS",home:"DEN",detail:"TUE · 8:00 PM CT · TNT",odds:"BOS -1.5"},{away:"GSW",home:"SAC",detail:"WED · 9:00 PM CT · ESPN",odds:"GSW +2.5"}],marquee:[{away:"BOS",home:"DEN",detail:"Championship-caliber opener"},{away:"LAL",home:"GSW",detail:"Friday showcase"}]},
{league:"MLB",headline:"WILD-CARD PRESSURE IS EVERYWHERE",summary:"Completed games, tonight's card and the most meaningful series share the same baseball page.",lead:{away:"HOU",home:"SEA",label:"LIVE · TOP 7",time:"4–3",odds:"HOU -1.5 · O/U 8.5"},results:[{away:"NYY",home:"BOS",score:"5–2",detail:"FINAL"},{away:"CHC",home:"STL",score:"6–4",detail:"FINAL"}],upcoming:[{away:"LAD",home:"SD",detail:"TONIGHT · 9:40 PM CT",odds:"LAD -125"},{away:"ATL",home:"NYM",detail:"FRI · 6:10 PM CT",odds:"ATL -1.5"}],marquee:[{away:"HOU",home:"SEA",detail:"AL West leverage game"},{away:"LAD",home:"SD",detail:"Late-window rivalry"}]},
{league:"NHL",headline:"THE WEEK'S ICE CARD BUILDS TOWARD SATURDAY",summary:"Recent finals, national broadcasts and rivalry games get more room than a single score row.",lead:{away:"EDM",home:"FLA",label:"HOCKEY NIGHT",time:"SAT · 7:30 PM CT",odds:"FLA -1.5 · O/U 6.5"},results:[{away:"COL",home:"DAL",score:"4–3",detail:"FINAL OT"},{away:"TOR",home:"MTL",score:"5–2",detail:"FINAL"}],upcoming:[{away:"EDM",home:"FLA",detail:"SAT · 7:30 PM CT · ESPN",odds:"FLA -135"},{away:"NYR",home:"NJD",detail:"SUN · 6:00 PM CT",odds:"NJD -120"}],marquee:[{away:"EDM",home:"FLA",detail:"Finals rematch energy"},{away:"TOR",home:"MTL",detail:"Original Six spotlight"}]},
{league:"NCAAF",headline:"SATURDAY IS BUILT AROUND THE TOP 25",summary:"National rankings, completed results, upcoming kickoff windows and Michigan's dedicated module work together without crowding each other.",lead:{away:"TEX",home:"MICH",label:"TOP-10 SHOWDOWN",time:"SAT · 11:00 AM CT",odds:"MICH -3.5 · O/U 44.5"},results:[{away:"UGA",home:"CLEM",score:"34–13",detail:"FINAL"},{away:"OSU",home:"ND",score:"27–21",detail:"FINAL"}],upcoming:[{away:"TEX",home:"MICH",detail:"SAT · 11:00 AM CT · FOX",odds:"MICH -3.5"},{away:"LSU",home:"USC",detail:"SAT · 6:30 PM CT · ESPN",odds:"LSU -2.5"}],marquee:[{away:"UGA",home:"ALA",detail:"SEC title-shaping game"},{away:"TEX",home:"MICH",detail:"Top-10 collision"}]},
{league:"F1",headline:"RACE CONTROL OWNS THE WEEKEND",summary:"Sessions, recent podiums, championship pressure and the next track window become the motorsport equivalent of a league page.",lead:{away:"NOR",home:"PIA",label:"BELGIAN GRAND PRIX",time:"SUN · 8:00 AM CT",odds:"NOR +180 · PIA +220"},results:[{away:"NOR",home:"PIA",score:"P1 / P2",detail:"LAST RACE"},{away:"VER",home:"RUS",score:"P3 / P4",detail:"LAST RACE"}],upcoming:[{away:"FP1",home:"SPA",detail:"FRI · 6:30 AM CT",odds:"DRY"},{away:"QUALI",home:"SPA",detail:"SAT · 9:00 AM CT",odds:"NOR +160"}],marquee:[{away:"TITLE",home:"FIGHT",detail:"Norris vs Piastri"},{away:"WEATHER",home:"WATCH",detail:"Rain threat Sunday"}]},
{league:"INDYCAR",headline:"THE TITLE FIGHT MOVES TO ROAD AMERICA",summary:"Recent finishes, session times and championship stakes receive the same editorial treatment as the major stick-and-ball leagues.",lead:{away:"PAL",home:"OWD",label:"ROAD AMERICA",time:"SUN · 2:00 PM CT",odds:"PAL +250 · OWD +400"},results:[{away:"PAL",home:"HRT",score:"P1 / P2",detail:"LAST RACE"},{away:"OWD",home:"MCL",score:"P3 / P4",detail:"LAST RACE"}],upcoming:[{away:"PRACTICE",home:"RA",detail:"FRI · 1:30 PM CT",odds:"—"},{away:"QUALI",home:"RA",detail:"SAT · 2:00 PM CT",odds:"PAL +225"}],marquee:[{away:"TITLE",home:"FIGHT",detail:"Palou protects the lead"},{away:"PASSING",home:"ZONE",detail:"Turn 5 strategy"}]}
],
top25:[{rank:1,team:"GEORGIA",code:"UGA",record:"1–0",move:"—"},{rank:2,team:"OHIO STATE",code:"OSU",record:"1–0",move:"—"},{rank:3,team:"TEXAS",code:"TEX",record:"1–0",move:"+1"},{rank:4,team:"OREGON",code:"ORE",record:"1–0",move:"-1"},{rank:5,team:"ALABAMA",code:"ALA",record:"1–0",move:"—"},{rank:6,team:"MICHIGAN",code:"MICH",record:"1–0",move:"+3"},{rank:7,team:"NOTRE DAME",code:"ND",record:"0–1",move:"-2"},{rank:8,team:"PENN STATE",code:"PSU",record:"1–0",move:"—"}],
top25Games:[{away:"TEX",home:"MICH",time:"SAT · 11:00 AM CT · FOX",note:"#3 at #6"},{away:"UGA",home:"ALA",time:"SAT · 6:30 PM CT · ABC",note:"#1 at #5"},{away:"ND",home:"PSU",time:"SAT · 2:30 PM CT · CBS",note:"#7 at #8"}],
michigan:{team:"MICHIGAN WOLVERINES",record:"1–0",ranking:"AP #6",conference:"BIG TEN",nextGame:{opponent:"TEXAS",start:"2026-09-12T16:00:00Z",network:"FOX",venue:"MICHIGAN STADIUM"},schedule:[{opponent:"TEXAS",start:"2026-09-12T16:00:00Z",site:"HOME"},{opponent:"USC",start:"2026-09-19T19:30:00Z",site:"AWAY"},{opponent:"MINNESOTA",start:"2026-09-26T16:00:00Z",site:"HOME"}],notes:["Michigan climbs to AP No. 6 after opening week","Texas visits for the week's largest top-10 game","All kickoff times are displayed in Dallas Central Time"]},stories:[["NFL","Football gets a real weekly desk instead of a thin score strip.","Last results, this week's slate, marquee games, logos and odds now live together."],["NCAAF","The AP Top 25 has its own command module.","Rankings, movers and top-ranked matchups now sit beside the national college football page."],["F1","Motorsport pages use the same editorial logic as every league.","Sessions, recent results and championship stakes rotate through Race Control."]]
};