window.SPORTS_DATA={events:[
{id:"DET-GB",league:"NFL",status:"UPCOMING",title:"NFC NORTH PRIME TIME",away:"DET",awayName:"LIONS",home:"GB",homeName:"PACKERS",start:"2026-09-13T00:20:00Z",venue:"LAMBEAU FIELD · GREEN BAY",network:"NBC",odds:{spread:"DET -2.5",moneyline:"DET -135 · GB +115",total:"O/U 47.5"}},
{id:"BOS-DEN",league:"NBA",status:"UPCOMING",title:"PRIMETIME BASKETBALL",away:"BOS",awayName:"CELTICS",home:"DEN",homeName:"NUGGETS",start:"2026-10-22T01:00:00Z",venue:"BALL ARENA · DENVER",network:"TNT",odds:{spread:"BOS -1.5",moneyline:"BOS -120 · DEN +105",total:"O/U 228.5"}},
{id:"HOU-SEA",league:"MLB",status:"LIVE · TOP 7",title:"AMERICAN LEAGUE SHOWDOWN",away:"HOU",awayName:"ASTROS",home:"SEA",homeName:"MARINERS",start:"2026-08-05T01:40:00Z",venue:"T-MOBILE PARK · SEATTLE",network:"MLB.TV",score:"4 — 3",detail:"TOP 7 · 1 OUT",odds:{spread:"HOU -1.5",moneyline:"HOU -125 · SEA +110",total:"O/U 8.5"}},
{id:"EDM-FLA",league:"NHL",status:"UPCOMING",title:"HOCKEY NIGHT",away:"EDM",awayName:"OILERS",home:"FLA",homeName:"PANTHERS",start:"2026-10-11T00:30:00Z",venue:"AMERANT BANK ARENA",network:"ESPN",odds:{spread:"FLA -1.5",moneyline:"EDM +115 · FLA -135",total:"O/U 6.5"}},
{id:"MICH-TEX",league:"NCAAF",status:"UPCOMING",title:"SATURDAY SPOTLIGHT",away:"TEX",awayName:"LONGHORNS",home:"MICH",homeName:"WOLVERINES",start:"2026-09-12T16:00:00Z",venue:"MICHIGAN STADIUM · ANN ARBOR",network:"FOX",odds:{spread:"MICH -3.5",moneyline:"MICH -165 · TEX +140",total:"O/U 44.5"}},
{id:"F1-SPA",league:"F1",status:"RACE WEEK",title:"BELGIAN GRAND PRIX",away:"NOR",awayName:"NORRIS",home:"PIA",homeName:"PIASTRI",start:"2026-08-30T13:00:00Z",venue:"SPA-FRANCORCHAMPS",network:"ESPN",detail:"LIGHTS OUT",odds:{spread:"WINNER",moneyline:"NOR +180 · PIA +220",total:"TOP 6 FINISH"}},
{id:"INDY-RA",league:"INDYCAR",status:"RACE WEEK",title:"ROAD AMERICA",away:"PAL",awayName:"PALOU",home:"OWD",homeName:"O’WARD",start:"2026-08-23T19:00:00Z",venue:"ELKHART LAKE, WISCONSIN",network:"FOX",detail:"GREEN FLAG",odds:{spread:"WINNER",moneyline:"PAL +250 · OWD +400",total:"TOP 5 FINISH"}}
],
tickerLanes:[
{league:"NFL",direction:"left"},{league:"NBA",direction:"right"},{league:"MLB",direction:"left"},{league:"NHL",direction:"right"},{league:"NCAAF",direction:"left"},{league:"F1",direction:"right"},{league:"INDYCAR",direction:"left"}],
michigan:{team:"MICHIGAN WOLVERINES",record:"0–0",ranking:"AP #9",conference:"BIG TEN",nextGame:{opponent:"TEXAS",start:"2026-09-12T16:00:00Z",network:"FOX",venue:"MICHIGAN STADIUM"},schedule:[{opponent:"TEXAS",start:"2026-09-12T16:00:00Z",site:"HOME"},{opponent:"USC",start:"2026-09-19T19:30:00Z",site:"AWAY"},{opponent:"MINNESOTA",start:"2026-09-26T16:00:00Z",site:"HOME"}],notes:["Michigan receives a dedicated schedule and information module","National college football remains visible across the score wall","All kickoff times are displayed in Dallas Central Time"]},
stories:[["NFL","The national slate comes alive under Central Command.","Every event, odds board, and ticker now speaks one time zone: Dallas Central Time."],["F1","Race Control gets a game-specific visual package.","Featured motorsport events use their own track image and timing language."],["NCAAF","Michigan keeps its private balcony without owning the whole stadium.","The Wolverines module remains dedicated while the national NCAA ticker stays universal."]]
};
